name: Create issues from TODOs

on:
  workflow_dispatch:
    inputs:
      importAll:
        default: false
        required: false
        type: boolean
  push:
    branches: # do not set multiple branches, todos might be added and then get referenced by themselves in case of a merge
      - main

permissions:
  issues: write
  repository-projects: read
  contents: read

jobs:
  todos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Issue Bot
        uses: juulsn/todo-issue@main
        with:
          autoAssign: True
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
